export const urlResources = "../resources/"
export const urlResourcesTyps = "../resources/tipos/"
export const urlSprites = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"
export const urlNotfound = "../resources/notFound.png"
export const urlPokeball = "../resources/pokeball.png"