export const Types = {
    NORMAL: 'normal',
    PLANTA: 'grass',
    FUEGO: 'fire',
    AGUA: 'water',
    VOLADOR: 'flying',
    ACERO: 'steel',
    BICHO: 'bug',
    DRAGON: 'dragon',
    ELECTRICO: 'electric',
    FANTASMA: 'shadow',
    HADA: 'fairy',
    HIELO: 'ice',
    PSIQUICO: 'psichic',
    ROCA: 'rock',
    SINIESTRO: 'dark',
    TIERRA: 'ground',
    VENENO: 'poison',
    PELEA: 'fighting'
}